image: ruby:2.6

cache:
  paths:
    - vendor/ruby

stages:
  - test

before_script:
  - ruby -v
  - bundle -v
  - bundle install --jobs $(nproc) --path vendor
  - apt-get install -y imagemagick
  - gem install mini_magick
  - gem install chunky_png

test:
  stage: test
  script:
    - bundle exec rake test
  environment:
    name: test